### ISSUE TITLE
你好，怎么提取cookie

### ISSUE THREAD

**Issue by woshichenchuana** [xjr7670/QQzone_crawler#1]
怎么提取cookie

**Comment by xjr7670** [comment]
在http://qzone.qq.com 页面，按F12打开浏览器的开发工具，然后输入你的QQ号和密码登录进去，然后点击URL为 http://user.qzone.qq.com/你的QQ号 的请求，在右边的Headers下，有个Request Headers，复制里面的Cookie对应的值就行了

**Comment by chen1399** [comment]
你好，我找不到URL为 http://user.qzone.qq.com/你的QQ号 的请求

**Comment by xjr7670** [comment]
你没找对吧。
在登录之前就要先打开F12，切换到Network，把Preserver log前面的勾去掉。然后再输入账号密码，然后再点登录，跳转之后的第一个请求记录了就是了。
如果是用的chrome，那么在请求记录那里显示的就只是你的QQ号码，它并不会直接显示完整的URL的。而当你把鼠标放上去的时候，它就会显示了，或者你点开它，看右边的headers，也会有

**Comment by mmmmmd** [comment]
good
