### ISSUE TITLE
运行时出错

### ISSUE THREAD

**Issue by 97classmate** [xjr7670/QQzone_crawler#10]
line 90, in parse_friends_url
    if qqnumber[0] == 0:
IndexError: string index out of range

**Comment by Freedomisgood** [comment]
你把cookie填入cookie_file文件就行了

**Comment by xjr7670** [comment]
@97classmate 很抱歉一直没有回复你。我把github邮件都放到一个文件夹里面，太多了，有时候我会一次性所有未读邮件都标记为已读，因此没有看到这个issue，直到楼上有人回复我才看到。

你这个错误应该是没有把cookie放到cookie_file里面。
多谢 @Freedomisgood

**Comment by 97classmate** [comment]
问题已经弄好了，但是还是要感谢你的分享。
