### ISSUE TITLE
好友文件0kb

### ISSUE THREAD

**Issue by llllevel5** [xjr7670/QQzone_crawler#11]
权限设置仅好友，cookies也设置无误，offset文件一直0kb.不知道该怎么解决

**Comment by xjr7670** [comment]
QQ空间的前端代码略有改变，项目代码已更新，重新pull后执行吧

**Comment by llllevel5** [comment]
感谢解答，不过还是未能解决，不知道是不是我win的配置问题 py版本3.6 win10 request1.0.2。

**Comment by xjr7670** [comment]
这个应该不影响。我前面测试过是没问题的，你可以先测试一下，利用util.py文件里面的headers，能不能登录上你的首页

**Comment by llllevel5** [comment]
浏览器标签页打开一瞬间会显示登陆成功，大概一秒后又会弹出快速登录选项

**Comment by llllevel5** [comment]
![qq 20181115155828](https://user-images.githubusercontent.com/22089110/48538638-f03a9900-e8ef-11e8-90a5-b9220e584259.png)这里会显示乱码 我换linux环境试一下
初学者哈哈，前面没理解你说的util.py文件里面的headers登录 抱歉:disappointed:

**Comment by xjr7670** [comment]
这个看上去是已经登录成功了的

**Comment by llllevel5** [comment]
:laughing: 有时候乱码有时候502bad getway 不管他了 谢谢解答:smiley:
