### ISSUE TITLE
Response [403]

### ISSUE THREAD

**Issue by yuppx** [xjr7670/QQzone_crawler#12]
在遇到了反爬取机制，请问有什么好的处理方法吗。
def __init__(self):

        self.headers = util.headers
        self.base_url = util.parse_friends_url()
        util.check_path('friends')
        print('开始获取好友列表，并把文件保存到 friends 文件夹')

    def get_friends(self):

        key = True
        position = 0
        while key:
            url = self.base_url + '&offset=' + str(position)
            referer = 'http://qzs.qq.com/qzone/v8/pages/setting/visit_v8.html'
            self.headers['Referer'] = referer

            print("\tDealing with position\t%d." % position)
            res = requests.get(url, headers=self.headers)
            print(url)
            html = res.text
            print(res)
            with open('friends/offset' + str(position) + '.json', 'w', encoding='utf-8') as f:
                f.write(html)

            # check whether the friend list is over
            # if that, the uinlist is void list
            with open('friends/offset' + str(position) + '.json', encoding='utf-8') as f2:
                con = f2.read()

我输出了一下res，显示为403

**Comment by xjr7670** [comment]
这种情况应该是登录失败了。 原因是因为在获取cookie中的p_skey用来生成g_tk值时出现的一个小bug导致的。

原来的代码我是默认p_skey值会出现在中间，于是用了查找开始和结束位置的方式来截取。但是今晚发现它可能会出现在末尾（此时找不到有效的结束位置，返回-1），这时候获取到的g_tk值就会跟QQ空间算法生成的不一致，此时登录会失败

问题已经修改，现在可以用来正常登录了。重新pull后执行吧
