### ISSUE TITLE
爬不了所有内容

### ISSUE THREAD

**Issue by lijufeng2016** [xjr7670/QQzone_crawler#2]
我试过你的代码了，爬虫只可以爬到一小部分的数据，不能爬到好友历史的所有说说，怎么破？

**Comment by xjr7670** [comment]
你看看日志，发生了些什么。或者单独爬一个好友的，看看得到什么结果

**Comment by lijufeng2016** [comment]
我把所有读写文件的操作加上encoding='utf-8'就行了
