### ISSUE TITLE
您好，我在阿里云上使用出现如下

### ISSUE THREAD

**Issue by github410117** [xjr7670/QQzone_crawler#3]
![image](https://user-images.githubusercontent.com/15375736/33863355-4233249e-df22-11e7-897a-39bf7bfa1a36.png)
cookie有写,运行python3 main.py就这样，立马就结束了!

**Comment by xjr7670** [comment]
你先看看当前目录下friends下面的文件里是什么内容
然后，你确认下，有没有先设置QQ空间的访问权限。这个程序是要先把自己的空间访问权限设置为QQ好友可访问，然后才能正常执行的

**Comment by github410117** [comment]
您好,我看了一下，friends下有个office0文件，打开其中为
![image](https://user-images.githubusercontent.com/15375736/33864263-e1ae7100-df26-11e7-8bf3-a3cd2cb00757.png)
我试了2个号都显示这个呢

**Comment by xjr7670** [comment]
QQ空间访问权限设置了没

**Comment by github410117** [comment]
我看了下，好像是都没有什么权限，都是选的所有人，我用了别人的一个cookie倒是成功了，估计是我自己空间哪里没对，我自己再研究一下

**Comment by xjr7670** [comment]
要把权限设置为仅QQ好友可见

**Comment by github410117** [comment]
恩，刚刚弄好了，估计就是这个问题，我设置成全部人了,已经在阿里云上跑起来了，谢谢
