### ISSUE TITLE
指定一些爬取限制条件

### ISSUE THREAD

**Issue by Mirrorrs** [xjr7670/QQzone_crawler#4]
你好，我想在爬取的时候加一条时间限制，限制在2017年开始到2018年春节之前，然后做一个词云，该在哪里修改代码？

**Comment by Hansoma** [comment]
好的 我去代码里面看一下，试试看，谢谢！

**Comment by skyfully** [comment]
您好我运行出现如下错误，还有请问自己的qq在哪里添加？
  File "F:\python_file\QQzone_crawler\util.py", line 72, in parse_friends_url
    if qqnumber[0] == 0:

IndexError: string index out of range
