### ISSUE TITLE
出错

### ISSUE THREAD

**Issue by skyfully** [xjr7670/QQzone_crawler#5]
您好，我运行出现如下错误，请问是什么原因

UnicodeEncodeError: 'gbk' codec can't encode character '\U0001f31f' in position 587: illegal multibyte sequence

**Comment by xjr7670** [comment]
你是不是用了python2了？
因为QQ空间里面包含有中文，如果用2的话，好多地方都有可能会遇到编码错误的。
你可以试试用python3运行
